import { v4 as uuid } from 'uuid';
import { formatDate } from '../utils/authUtils';

/**
 * Posts can be added here.
 * You can add default posts of your wish with different attributes
 * */

// export const posts = [
//   {
//     _id: 'fsjfhjsdh434jhsjd3',
//     pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652342774/photo-1652298926911-9d628f82e7de_xnxfvn.jpg',
//     content:
//       'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam veniam, voluptates illum repellendus vitae blanditiis voluptatum omnis reprehenderit corrupti officia.',
//     likes: {
//       likeCount: 0,
//       likedBy: [],
//       dislikedBy: [],
//     },
//     comments: [],
//     userId: 'asassdafdgdk',
//     createdAt: '2022-01-25T10:38:12+05:30',
//     updatedAt: formatDate(),
//   },
//   {
//     _id: '343asa232sfdgt45',
//     content:
//       'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, esse.',
//     pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652342874/photo-1652335223113-9919b4e052d5_ecguab.jpg',
//     likes: {
//       likeCount: 0,
//       likedBy: [],
//       dislikedBy: [],
//     },
//     comments: [],
//     userId: 'asassdafdgdk',
//     createdAt: '2022-01-25T10:38:12+05:30',
//     updatedAt: formatDate(),
//   },
// ];

export const posts = [
  {
    _id: 'fsjfhjsdh434jhsjd3',
    pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652342774/photo-1652298926911-9d628f82e7de_xnxfvn.jpg',
    content:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam veniam, voluptates illum repellendus vitae blanditiis voluptatum omnis reprehenderit corrupti officia.',
    likes: {
      likeCount: 1,
      likedBy: [
        {
          _id: 'asassdafdgdk',
          firstName: 'Rohan',
          lastName: 'Mondal',
          username: 'rohan@gmail.com',
          password: '1234abcd',
          createdAt: '2022-01-25T10:38:12+05:30',
          updatedAt: '2022-05-14T17:45:46+05:30',
          userHandler: 'rohan',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
          link: 'https://rohanspage.netlify.app',
          bio: 'Aspiring Software Developer',
          followers: [],
          following: [
            {
              _id: 'asassddsd243434',
              firstName: 'Rajani',
              lastName: 'Ghosh',
              username: 'rajanighosh@gmail.com',
              password: '1234abcd',
              createdAt: '2022-03-21T10:12:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rajani',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
              link: 'https://rajani.netlify.app',
              bio: 'Social Media Influencer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '2',
            },
            {
              _id: 'asassddfd232fgfg323',
              firstName: 'Subhash',
              lastName: 'Dugar',
              username: 'suhashdugar@gmail.com',
              password: '1234asdf',
              createdAt: '2022-04-09T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'subhashdugar',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
              link: 'https://subhasdugar.netlify.app',
              bio: 'Web Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '4',
            },
            {
              _id: 'asassddfd23dgdg334df',
              firstName: 'Sarita',
              lastName: 'Chandra',
              username: 'sarithachandra@gmail.com',
              password: '1234asdf09',
              createdAt: '2022-03-19T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'saritachandra',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg',
              link: 'https://sarithachandra.netlify.app',
              bio: 'SDE-1 at Invact',
              followers: [],
              following: [],
              bookmarks: [],
              id: '7',
            },
          ],
          bookmarks: [],
          id: '1',
        },
      ],
      dislikedBy: [],
    },
    comments: [],
    userId: 'asassdafdgdk',
    createdAt: '2022-01-25T10:38:12+05:30',
    updatedAt: '2022-05-14T18:03:52+05:30',
    id: '1',
  },
  {
    _id: '343asa232sfdgt45',
    content:
      'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, esse.',
    pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652342874/photo-1652335223113-9919b4e052d5_ecguab.jpg',
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    comments: [],
    userId: 'asassdafdgdk',
    createdAt: '2022-01-25T10:38:12+05:30',
    updatedAt: '2022-05-14T17:44:37+05:30',
    id: '2',
  },
  {
    _id: '4dda917b-6dda-48ad-97da-090c8843d6c5',
    content: 'Hey Today I created an app called Socially😎',
    pic: '',
    userId: 'asassdafdgdk',
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: 'asassddsd243434',
          firstName: 'Rajani',
          lastName: 'Ghosh',
          username: 'rajanighosh@gmail.com',
          password: '1234abcd',
          createdAt: '2022-03-21T10:12:12+05:30',
          updatedAt: '2022-05-14T17:45:42+05:30',
          userHandler: 'rajani',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
          link: 'https://rajani.netlify.app',
          bio: 'Social Media Influencer',
          followers: [
            {
              _id: 'asassdafdgdk',
              firstName: 'Rohan',
              lastName: 'Mondal',
              username: 'rohan@gmail.com',
              password: '1234abcd',
              createdAt: '2022-01-25T10:38:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rohan',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
              link: 'https://rohanspage.netlify.app',
              bio: 'Aspiring Software Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '1',
            },
          ],
          following: [],
          bookmarks: [],
          id: '2',
        },
        {
          _id: 'asassdafdgdk',
          firstName: 'Rohan',
          lastName: 'Mondal',
          username: 'rohan@gmail.com',
          password: '1234abcd',
          createdAt: '2022-01-25T10:38:12+05:30',
          updatedAt: '2022-05-14T17:45:46+05:30',
          userHandler: 'rohan',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
          link: 'https://rohanspage.netlify.app',
          bio: 'Aspiring Software Developer',
          followers: [],
          following: [
            {
              _id: 'asassddsd243434',
              firstName: 'Rajani',
              lastName: 'Ghosh',
              username: 'rajanighosh@gmail.com',
              password: '1234abcd',
              createdAt: '2022-03-21T10:12:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rajani',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
              link: 'https://rajani.netlify.app',
              bio: 'Social Media Influencer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '2',
            },
            {
              _id: 'asassddfd232fgfg323',
              firstName: 'Subhash',
              lastName: 'Dugar',
              username: 'suhashdugar@gmail.com',
              password: '1234asdf',
              createdAt: '2022-04-09T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'subhashdugar',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
              link: 'https://subhasdugar.netlify.app',
              bio: 'Web Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '4',
            },
            {
              _id: 'asassddfd23dgdg334df',
              firstName: 'Sarita',
              lastName: 'Chandra',
              username: 'sarithachandra@gmail.com',
              password: '1234asdf09',
              createdAt: '2022-03-19T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'saritachandra',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg',
              link: 'https://sarithachandra.netlify.app',
              bio: 'SDE-1 at Invact',
              followers: [],
              following: [],
              bookmarks: [],
              id: '7',
            },
          ],
          bookmarks: [],
          id: '1',
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: '41d3cab7-8d31-499b-a393-b94efcd8f31b',
        content: 'Nice I am currently using it',
        postId: '4dda917b-6dda-48ad-97da-090c8843d6c5',
        user: {
          _id: 'asassddsd243434',
          firstName: 'Rajani',
          lastName: 'Ghosh',
          username: 'rajanighosh@gmail.com',
          password: '1234abcd',
          createdAt: '2022-03-21T10:12:12+05:30',
          updatedAt: '2022-05-14T17:45:42+05:30',
          userHandler: 'rajani',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
          link: 'https://rajani.netlify.app',
          bio: 'Social Media Influencer',
          followers: [
            {
              _id: 'asassdafdgdk',
              firstName: 'Rohan',
              lastName: 'Mondal',
              username: 'rohan@gmail.com',
              password: '1234abcd',
              createdAt: '2022-01-25T10:38:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rohan',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
              link: 'https://rohanspage.netlify.app',
              bio: 'Aspiring Software Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '1',
            },
          ],
          following: [],
          bookmarks: [],
          id: '2',
        },
        replies: [],
        votes: {
          upvotedBy: [],
        },
        createdAt: '2022-05-14T17:46:17+05:30',
        updatedAt: '2022-05-14T17:46:17+05:30',
      },
    ],
    username: 'rohan@gmail.com',
    createdAt: '2022-05-14T17:45:26+05:30',
    updatedAt: '2022-05-14T18:03:48+05:30',
    id: '3',
  },
  {
    _id: 'b1373ff1-1e05-467f-9efd-de2286fa42a9',
    content: 'Just using Socially, It is cool😎',
    pic: '',
    userId: 'asassddsd243434',
    likes: {
      likeCount: 1,
      likedBy: [
        {
          _id: 'asassdafdgdk',
          firstName: 'Rohan',
          lastName: 'Mondal',
          username: 'rohan@gmail.com',
          password: '1234abcd',
          createdAt: '2022-01-25T10:38:12+05:30',
          updatedAt: '2022-05-14T17:45:46+05:30',
          userHandler: 'rohan',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
          link: 'https://rohanspage.netlify.app',
          bio: 'Aspiring Software Developer',
          followers: [],
          following: [
            {
              _id: 'asassddsd243434',
              firstName: 'Rajani',
              lastName: 'Ghosh',
              username: 'rajanighosh@gmail.com',
              password: '1234abcd',
              createdAt: '2022-03-21T10:12:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rajani',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
              link: 'https://rajani.netlify.app',
              bio: 'Social Media Influencer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '2',
            },
            {
              _id: 'asassddfd232fgfg323',
              firstName: 'Subhash',
              lastName: 'Dugar',
              username: 'suhashdugar@gmail.com',
              password: '1234asdf',
              createdAt: '2022-04-09T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'subhashdugar',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
              link: 'https://subhasdugar.netlify.app',
              bio: 'Web Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '4',
            },
            {
              _id: 'asassddfd23dgdg334df',
              firstName: 'Sarita',
              lastName: 'Chandra',
              username: 'sarithachandra@gmail.com',
              password: '1234asdf09',
              createdAt: '2022-03-19T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'saritachandra',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg',
              link: 'https://sarithachandra.netlify.app',
              bio: 'SDE-1 at Invact',
              followers: [],
              following: [],
              bookmarks: [],
              id: '7',
            },
          ],
          bookmarks: [],
          id: '1',
        },
      ],
      dislikedBy: [],
    },
    comments: [],
    username: 'rajanighosh@gmail.com',
    createdAt: '2022-05-14T17:46:37+05:30',
    updatedAt: '2022-05-14T18:03:46+05:30',
    id: '4',
  },
  {
    _id: '8d8b86e9-a0d5-43f8-8435-2d636d665a60',
    content:
      "I can't tell what is going on with me. I have just 2 months for my HS. Have not completed a single chapter in chemistry!!!🥶",
    pic: '',
    userId: 'asassddsd243434',
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: 'asassddfdsfdgsd32323',
          firstName: 'Devika',
          lastName: 'Gill',
          username: 'devikagill@gmail.com',
          password: '1234asdf',
          createdAt: '2022-05-12T08:30:12+05:30',
          updatedAt: '2022-05-14T17:44:37+05:30',
          userHandler: 'devikaGill',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg',
          link: 'https://devikagill.netlify.app',
          bio: 'Web Designer',
          followers: [],
          following: [],
          bookmarks: [],
          id: '3',
        },
        {
          _id: 'asassdafdgdk',
          firstName: 'Rohan',
          lastName: 'Mondal',
          username: 'rohan@gmail.com',
          password: '1234abcd',
          createdAt: '2022-01-25T10:38:12+05:30',
          updatedAt: '2022-05-14T17:45:46+05:30',
          userHandler: 'rohan',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
          link: 'https://rohanspage.netlify.app',
          bio: 'Aspiring Software Developer',
          followers: [],
          following: [
            {
              _id: 'asassddsd243434',
              firstName: 'Rajani',
              lastName: 'Ghosh',
              username: 'rajanighosh@gmail.com',
              password: '1234abcd',
              createdAt: '2022-03-21T10:12:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rajani',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
              link: 'https://rajani.netlify.app',
              bio: 'Social Media Influencer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '2',
            },
            {
              _id: 'asassddfd232fgfg323',
              firstName: 'Subhash',
              lastName: 'Dugar',
              username: 'suhashdugar@gmail.com',
              password: '1234asdf',
              createdAt: '2022-04-09T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'subhashdugar',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
              link: 'https://subhasdugar.netlify.app',
              bio: 'Web Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '4',
            },
            {
              _id: 'asassddfd23dgdg334df',
              firstName: 'Sarita',
              lastName: 'Chandra',
              username: 'sarithachandra@gmail.com',
              password: '1234asdf09',
              createdAt: '2022-03-19T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'saritachandra',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg',
              link: 'https://sarithachandra.netlify.app',
              bio: 'SDE-1 at Invact',
              followers: [],
              following: [],
              bookmarks: [],
              id: '7',
            },
          ],
          bookmarks: [],
          id: '1',
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: '4d3dd78e-3a4d-4e13-a917-c01df3a624ce',
        content: 'Maybe I can help you contact me',
        postId: '8d8b86e9-a0d5-43f8-8435-2d636d665a60',
        user: {
          _id: 'asassddfdsfdgsd32323',
          firstName: 'Devika',
          lastName: 'Gill',
          username: 'devikagill@gmail.com',
          password: '1234asdf',
          createdAt: '2022-05-12T08:30:12+05:30',
          updatedAt: '2022-05-14T17:44:37+05:30',
          userHandler: 'devikaGill',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg',
          link: 'https://devikagill.netlify.app',
          bio: 'Web Designer',
          followers: [],
          following: [],
          bookmarks: [],
          id: '3',
        },
        replies: [],
        votes: {
          upvotedBy: [],
        },
        createdAt: '2022-05-14T17:52:36+05:30',
        updatedAt: '2022-05-14T17:52:36+05:30',
      },
    ],
    username: 'rajanighosh@gmail.com',
    createdAt: '2022-05-14T17:47:23+05:30',
    updatedAt: '2022-05-14T18:03:44+05:30',
    id: '5',
  },
  {
    _id: 'dbe06b44-632a-45dc-bee9-ae60e4617339',
    content:
      "Just got my 12th marksheet ... it is not good. Don't know if I able to take CS or not",
    pic: '',
    userId: 'asassddfdsfdgsd32323',
    likes: {
      likeCount: 2,
      likedBy: [
        {
          _id: 'asassddfd232fgfg323',
          firstName: 'Subhash',
          lastName: 'Dugar',
          username: 'suhashdugar@gmail.com',
          password: '1234asdf',
          createdAt: '2022-04-09T09:30:12+05:30',
          updatedAt: '2022-05-14T17:45:43+05:30',
          userHandler: 'subhashdugar',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
          link: 'https://subhasdugar.netlify.app',
          bio: 'Web Developer',
          followers: [
            {
              _id: 'asassdafdgdk',
              firstName: 'Rohan',
              lastName: 'Mondal',
              username: 'rohan@gmail.com',
              password: '1234abcd',
              createdAt: '2022-01-25T10:38:12+05:30',
              updatedAt: '2022-05-14T17:45:43+05:30',
              userHandler: 'rohan',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
              link: 'https://rohanspage.netlify.app',
              bio: 'Aspiring Software Developer',
              followers: [],
              following: [
                {
                  _id: 'asassddsd243434',
                  firstName: 'Rajani',
                  lastName: 'Ghosh',
                  username: 'rajanighosh@gmail.com',
                  password: '1234abcd',
                  createdAt: '2022-03-21T10:12:12+05:30',
                  updatedAt: '2022-05-14T17:44:37+05:30',
                  userHandler: 'rajani',
                  pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
                  link: 'https://rajani.netlify.app',
                  bio: 'Social Media Influencer',
                  followers: [],
                  following: [],
                  bookmarks: [],
                  id: '2',
                },
              ],
              bookmarks: [],
              id: '1',
            },
          ],
          following: [],
          bookmarks: [],
          id: '4',
        },
        {
          _id: 'asassddsd243434',
          firstName: 'Rajani',
          lastName: 'Ghosh',
          username: 'rajanighosh@gmail.com',
          password: '1234abcd',
          createdAt: '2022-03-21T10:12:12+05:30',
          updatedAt: '2022-05-14T17:45:42+05:30',
          userHandler: 'rajani',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
          link: 'https://rajani.netlify.app',
          bio: 'Social Media Influencer',
          followers: [
            {
              _id: 'asassdafdgdk',
              firstName: 'Rohan',
              lastName: 'Mondal',
              username: 'rohan@gmail.com',
              password: '1234abcd',
              createdAt: '2022-01-25T10:38:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rohan',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
              link: 'https://rohanspage.netlify.app',
              bio: 'Aspiring Software Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '1',
            },
          ],
          following: [],
          bookmarks: [],
          id: '2',
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: '2594f4a0-06aa-497f-b64e-2efff1462fa2',
        content: 'Hey why not thinking about Bangalore as you want to take CS',
        postId: 'dbe06b44-632a-45dc-bee9-ae60e4617339',
        user: {
          _id: 'asassddfd232fgfg323',
          firstName: 'Subhash',
          lastName: 'Dugar',
          username: 'suhashdugar@gmail.com',
          password: '1234asdf',
          createdAt: '2022-04-09T09:30:12+05:30',
          updatedAt: '2022-05-14T17:45:43+05:30',
          userHandler: 'subhashdugar',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
          link: 'https://subhasdugar.netlify.app',
          bio: 'Web Developer',
          followers: [
            {
              _id: 'asassdafdgdk',
              firstName: 'Rohan',
              lastName: 'Mondal',
              username: 'rohan@gmail.com',
              password: '1234abcd',
              createdAt: '2022-01-25T10:38:12+05:30',
              updatedAt: '2022-05-14T17:45:43+05:30',
              userHandler: 'rohan',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
              link: 'https://rohanspage.netlify.app',
              bio: 'Aspiring Software Developer',
              followers: [],
              following: [
                {
                  _id: 'asassddsd243434',
                  firstName: 'Rajani',
                  lastName: 'Ghosh',
                  username: 'rajanighosh@gmail.com',
                  password: '1234abcd',
                  createdAt: '2022-03-21T10:12:12+05:30',
                  updatedAt: '2022-05-14T17:44:37+05:30',
                  userHandler: 'rajani',
                  pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
                  link: 'https://rajani.netlify.app',
                  bio: 'Social Media Influencer',
                  followers: [],
                  following: [],
                  bookmarks: [],
                  id: '2',
                },
              ],
              bookmarks: [],
              id: '1',
            },
          ],
          following: [],
          bookmarks: [],
          id: '4',
        },
        replies: [],
        votes: {
          upvotedBy: [],
        },
        createdAt: '2022-05-14T17:54:43+05:30',
        updatedAt: '2022-05-14T17:54:43+05:30',
      },
      {
        _id: 'f6288e59-40ea-4c84-b4e8-fa54adf0c473',
        content: "Don't worry Neogcamp is there",
        postId: 'dbe06b44-632a-45dc-bee9-ae60e4617339',
        user: {
          _id: 'asassdafdgdk',
          firstName: 'Rohan',
          lastName: 'Mondal',
          username: 'rohan@gmail.com',
          password: '1234abcd',
          createdAt: '2022-01-25T10:38:12+05:30',
          updatedAt: '2022-05-14T17:45:46+05:30',
          userHandler: 'rohan',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
          link: 'https://rohanspage.netlify.app',
          bio: 'Aspiring Software Developer',
          followers: [],
          following: [
            {
              _id: 'asassddsd243434',
              firstName: 'Rajani',
              lastName: 'Ghosh',
              username: 'rajanighosh@gmail.com',
              password: '1234abcd',
              createdAt: '2022-03-21T10:12:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rajani',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
              link: 'https://rajani.netlify.app',
              bio: 'Social Media Influencer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '2',
            },
            {
              _id: 'asassddfd232fgfg323',
              firstName: 'Subhash',
              lastName: 'Dugar',
              username: 'suhashdugar@gmail.com',
              password: '1234asdf',
              createdAt: '2022-04-09T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'subhashdugar',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
              link: 'https://subhasdugar.netlify.app',
              bio: 'Web Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '4',
            },
            {
              _id: 'asassddfd23dgdg334df',
              firstName: 'Sarita',
              lastName: 'Chandra',
              username: 'sarithachandra@gmail.com',
              password: '1234asdf09',
              createdAt: '2022-03-19T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'saritachandra',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg',
              link: 'https://sarithachandra.netlify.app',
              bio: 'SDE-1 at Invact',
              followers: [],
              following: [],
              bookmarks: [],
              id: '7',
            },
          ],
          bookmarks: [],
          id: '1',
        },
        replies: [],
        votes: {
          upvotedBy: [],
        },
        createdAt: '2022-05-14T18:03:13+05:30',
        updatedAt: '2022-05-14T18:03:23+05:30',
      },
    ],
    username: 'devikagill@gmail.com',
    createdAt: '2022-05-14T17:53:49+05:30',
    updatedAt: '2022-05-14T17:58:46+05:30',
    id: '6',
  },
  {
    _id: '05a72f8f-7af6-4aea-bbc0-bbcbafd7f893',
    content:
      'Just came Bangalore for college purpose. Weather is so good. College is good. I think I can start again my journey',
    pic: '',
    userId: 'asassddfd232fgfg323',
    likes: {
      likeCount: 1,
      likedBy: [
        {
          _id: 'asassddsd243434',
          firstName: 'Rajani',
          lastName: 'Ghosh',
          username: 'rajanighosh@gmail.com',
          password: '1234abcd',
          createdAt: '2022-03-21T10:12:12+05:30',
          updatedAt: '2022-05-14T17:45:42+05:30',
          userHandler: 'rajani',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
          link: 'https://rajani.netlify.app',
          bio: 'Social Media Influencer',
          followers: [
            {
              _id: 'asassdafdgdk',
              firstName: 'Rohan',
              lastName: 'Mondal',
              username: 'rohan@gmail.com',
              password: '1234abcd',
              createdAt: '2022-01-25T10:38:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rohan',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
              link: 'https://rohanspage.netlify.app',
              bio: 'Aspiring Software Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '1',
            },
          ],
          following: [],
          bookmarks: [],
          id: '2',
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: '1ad97573-3ada-4ee0-a6f0-4b90abe8e74c',
        content: 'Nice can u give me some tips, how to start coding',
        postId: '05a72f8f-7af6-4aea-bbc0-bbcbafd7f893',
        user: {
          _id: 'asassddsd243434',
          firstName: 'Rajani',
          lastName: 'Ghosh',
          username: 'rajanighosh@gmail.com',
          password: '1234abcd',
          createdAt: '2022-03-21T10:12:12+05:30',
          updatedAt: '2022-05-14T17:45:42+05:30',
          userHandler: 'rajani',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
          link: 'https://rajani.netlify.app',
          bio: 'Social Media Influencer',
          followers: [
            {
              _id: 'asassdafdgdk',
              firstName: 'Rohan',
              lastName: 'Mondal',
              username: 'rohan@gmail.com',
              password: '1234abcd',
              createdAt: '2022-01-25T10:38:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rohan',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
              link: 'https://rohanspage.netlify.app',
              bio: 'Aspiring Software Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '1',
            },
          ],
          following: [],
          bookmarks: [],
          id: '2',
        },
        replies: [
          {
            _id: '056a7821-d6af-4624-a368-bd60ba14237a',
            user: {
              _id: 'asassdafdgdk',
              firstName: 'Rohan',
              lastName: 'Mondal',
              username: 'rohan@gmail.com',
              createdAt: '2022-01-25T10:38:12+05:30',
              updatedAt: '2022-05-14T17:45:46+05:30',
              userHandler: 'rohan',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
              link: 'https://rohanspage.netlify.app',
              bio: 'Aspiring Software Developer',
              followers: [],
              following: [
                {
                  _id: 'asassddsd243434',
                  firstName: 'Rajani',
                  lastName: 'Ghosh',
                  username: 'rajanighosh@gmail.com',
                  password: '1234abcd',
                  createdAt: '2022-03-21T10:12:12+05:30',
                  updatedAt: '2022-05-14T17:44:37+05:30',
                  userHandler: 'rajani',
                  pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
                  link: 'https://rajani.netlify.app',
                  bio: 'Social Media Influencer',
                  followers: [],
                  following: [],
                  bookmarks: [],
                  id: '2',
                },
                {
                  _id: 'asassddfd232fgfg323',
                  firstName: 'Subhash',
                  lastName: 'Dugar',
                  username: 'suhashdugar@gmail.com',
                  password: '1234asdf',
                  createdAt: '2022-04-09T09:30:12+05:30',
                  updatedAt: '2022-05-14T17:44:37+05:30',
                  userHandler: 'subhashdugar',
                  pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
                  link: 'https://subhasdugar.netlify.app',
                  bio: 'Web Developer',
                  followers: [],
                  following: [],
                  bookmarks: [],
                  id: '4',
                },
                {
                  _id: 'asassddfd23dgdg334df',
                  firstName: 'Sarita',
                  lastName: 'Chandra',
                  username: 'sarithachandra@gmail.com',
                  password: '1234asdf09',
                  createdAt: '2022-03-19T09:30:12+05:30',
                  updatedAt: '2022-05-14T17:44:37+05:30',
                  userHandler: 'saritachandra',
                  pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg',
                  link: 'https://sarithachandra.netlify.app',
                  bio: 'SDE-1 at Invact',
                  followers: [],
                  following: [],
                  bookmarks: [],
                  id: '7',
                },
              ],
              bookmarks: [],
              id: '1',
            },
            content: 'Ping me , may be I can help',
          },
        ],
        votes: {
          upvotedBy: [],
        },
        createdAt: '2022-05-14T17:56:39+05:30',
        updatedAt: '2022-05-14T18:02:14+05:30',
      },
      {
        _id: 'c03d5596-9eed-4d7e-9f65-eaa3fd92e982',
        content: 'Cool bro',
        postId: '05a72f8f-7af6-4aea-bbc0-bbcbafd7f893',
        user: {
          _id: 'asassdafdgdk',
          firstName: 'Rohan',
          lastName: 'Mondal',
          username: 'rohan@gmail.com',
          password: '1234abcd',
          createdAt: '2022-01-25T10:38:12+05:30',
          updatedAt: '2022-05-14T17:45:46+05:30',
          userHandler: 'rohan',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
          link: 'https://rohanspage.netlify.app',
          bio: 'Aspiring Software Developer',
          followers: [],
          following: [
            {
              _id: 'asassddsd243434',
              firstName: 'Rajani',
              lastName: 'Ghosh',
              username: 'rajanighosh@gmail.com',
              password: '1234abcd',
              createdAt: '2022-03-21T10:12:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rajani',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
              link: 'https://rajani.netlify.app',
              bio: 'Social Media Influencer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '2',
            },
            {
              _id: 'asassddfd232fgfg323',
              firstName: 'Subhash',
              lastName: 'Dugar',
              username: 'suhashdugar@gmail.com',
              password: '1234asdf',
              createdAt: '2022-04-09T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'subhashdugar',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
              link: 'https://subhasdugar.netlify.app',
              bio: 'Web Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '4',
            },
            {
              _id: 'asassddfd23dgdg334df',
              firstName: 'Sarita',
              lastName: 'Chandra',
              username: 'sarithachandra@gmail.com',
              password: '1234asdf09',
              createdAt: '2022-03-19T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'saritachandra',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg',
              link: 'https://sarithachandra.netlify.app',
              bio: 'SDE-1 at Invact',
              followers: [],
              following: [],
              bookmarks: [],
              id: '7',
            },
          ],
          bookmarks: [],
          id: '1',
        },
        replies: [],
        votes: {
          upvotedBy: [],
        },
        createdAt: '2022-05-14T18:01:59+05:30',
        updatedAt: '2022-05-14T18:01:59+05:30',
      },
    ],
    username: 'suhashdugar@gmail.com',
    createdAt: '2022-05-14T17:56:02+05:30',
    updatedAt: '2022-05-14T17:56:23+05:30',
    id: '7',
  },
  {
    _id: '75f2e575-357d-417b-96ca-bf21febc27a9',
    content:
      'Learned Python, but ML seems harder! Can anyone help me to choose path , ML or Development🤯',
    pic: '',
    userId: 'asassddsd243434',
    likes: {
      likeCount: 1,
      likedBy: [
        {
          _id: 'asassddfdsfdgsd32323',
          firstName: 'Devika',
          lastName: 'Gill',
          username: 'devikagill@gmail.com',
          password: '1234asdf',
          createdAt: '2022-05-12T08:30:12+05:30',
          updatedAt: '2022-05-14T17:44:37+05:30',
          userHandler: 'devikaGill',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg',
          link: 'https://devikagill.netlify.app',
          bio: 'Web Designer',
          followers: [],
          following: [],
          bookmarks: [],
          id: '3',
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: '4cdadb85-8cd0-4e6d-a377-acdc35f4a774',
        content: 'Sure , contact me',
        postId: '75f2e575-357d-417b-96ca-bf21febc27a9',
        user: {
          _id: 'asassddfdsfdgsd32323',
          firstName: 'Devika',
          lastName: 'Gill',
          username: 'devikagill@gmail.com',
          password: '1234asdf',
          createdAt: '2022-05-12T08:30:12+05:30',
          updatedAt: '2022-05-14T17:44:37+05:30',
          userHandler: 'devikaGill',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425124/images_u2sypk.jpg',
          link: 'https://devikagill.netlify.app',
          bio: 'Web Designer',
          followers: [],
          following: [],
          bookmarks: [],
          id: '3',
        },
        replies: [],
        votes: {
          upvotedBy: [],
        },
        createdAt: '2022-05-14T17:59:37+05:30',
        updatedAt: '2022-05-14T17:59:37+05:30',
      },
      {
        _id: '9b7a1c64-37f5-4e10-9694-3243301617cf',
        content: 'Better to see the overall view and choose wisely',
        postId: '75f2e575-357d-417b-96ca-bf21febc27a9',
        user: {
          _id: 'asassdafdgdk',
          firstName: 'Rohan',
          lastName: 'Mondal',
          username: 'rohan@gmail.com',
          password: '1234abcd',
          createdAt: '2022-01-25T10:38:12+05:30',
          updatedAt: '2022-05-14T17:45:46+05:30',
          userHandler: 'rohan',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
          link: 'https://rohanspage.netlify.app',
          bio: 'Aspiring Software Developer',
          followers: [],
          following: [
            {
              _id: 'asassddsd243434',
              firstName: 'Rajani',
              lastName: 'Ghosh',
              username: 'rajanighosh@gmail.com',
              password: '1234abcd',
              createdAt: '2022-03-21T10:12:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'rajani',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
              link: 'https://rajani.netlify.app',
              bio: 'Social Media Influencer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '2',
            },
            {
              _id: 'asassddfd232fgfg323',
              firstName: 'Subhash',
              lastName: 'Dugar',
              username: 'suhashdugar@gmail.com',
              password: '1234asdf',
              createdAt: '2022-04-09T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'subhashdugar',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
              link: 'https://subhasdugar.netlify.app',
              bio: 'Web Developer',
              followers: [],
              following: [],
              bookmarks: [],
              id: '4',
            },
            {
              _id: 'asassddfd23dgdg334df',
              firstName: 'Sarita',
              lastName: 'Chandra',
              username: 'sarithachandra@gmail.com',
              password: '1234asdf09',
              createdAt: '2022-03-19T09:30:12+05:30',
              updatedAt: '2022-05-14T17:44:37+05:30',
              userHandler: 'saritachandra',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652427968/images_dmm7fi.jpg',
              link: 'https://sarithachandra.netlify.app',
              bio: 'SDE-1 at Invact',
              followers: [],
              following: [],
              bookmarks: [],
              id: '7',
            },
          ],
          bookmarks: [],
          id: '1',
        },
        replies: [],
        votes: {
          upvotedBy: [],
        },
        createdAt: '2022-05-14T18:02:48+05:30',
        updatedAt: '2022-05-14T18:02:48+05:30',
      },
    ],
    username: 'rajanighosh@gmail.com',
    createdAt: '2022-05-14T17:58:41+05:30',
    updatedAt: '2022-05-14T17:59:22+05:30',
    id: '8',
  },
  {
    _id: '80635873-6800-4119-8c2c-f99919df6cbc',
    content: 'DSA is cool as well as frustrated sometimes',
    pic: '',
    userId: 'asassddfdsfdgsd32323',
    likes: {
      likeCount: 1,
      likedBy: [
        {
          _id: 'asassddfd232fgfg323',
          firstName: 'Subhash',
          lastName: 'Dugar',
          username: 'suhashdugar@gmail.com',
          password: '1234asdf',
          createdAt: '2022-04-09T09:30:12+05:30',
          updatedAt: '2022-05-14T17:45:43+05:30',
          userHandler: 'subhashdugar',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
          link: 'https://subhasdugar.netlify.app',
          bio: 'Web Developer',
          followers: [
            {
              _id: 'asassdafdgdk',
              firstName: 'Rohan',
              lastName: 'Mondal',
              username: 'rohan@gmail.com',
              password: '1234abcd',
              createdAt: '2022-01-25T10:38:12+05:30',
              updatedAt: '2022-05-14T17:45:43+05:30',
              userHandler: 'rohan',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
              link: 'https://rohanspage.netlify.app',
              bio: 'Aspiring Software Developer',
              followers: [],
              following: [
                {
                  _id: 'asassddsd243434',
                  firstName: 'Rajani',
                  lastName: 'Ghosh',
                  username: 'rajanighosh@gmail.com',
                  password: '1234abcd',
                  createdAt: '2022-03-21T10:12:12+05:30',
                  updatedAt: '2022-05-14T17:44:37+05:30',
                  userHandler: 'rajani',
                  pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
                  link: 'https://rajani.netlify.app',
                  bio: 'Social Media Influencer',
                  followers: [],
                  following: [],
                  bookmarks: [],
                  id: '2',
                },
              ],
              bookmarks: [],
              id: '1',
            },
          ],
          following: [],
          bookmarks: [],
          id: '4',
        },
      ],
      dislikedBy: [],
    },
    comments: [
      {
        _id: '1261c9c1-0a2f-49d6-808f-b4d23d1342af',
        content: 'For me today it is so frustrating',
        postId: '80635873-6800-4119-8c2c-f99919df6cbc',
        user: {
          _id: 'asassddfd232fgfg323',
          firstName: 'Subhash',
          lastName: 'Dugar',
          username: 'suhashdugar@gmail.com',
          password: '1234asdf',
          createdAt: '2022-04-09T09:30:12+05:30',
          updatedAt: '2022-05-14T17:45:43+05:30',
          userHandler: 'subhashdugar',
          pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652425327/images_jt3uha.jpg',
          link: 'https://subhasdugar.netlify.app',
          bio: 'Web Developer',
          followers: [
            {
              _id: 'asassdafdgdk',
              firstName: 'Rohan',
              lastName: 'Mondal',
              username: 'rohan@gmail.com',
              password: '1234abcd',
              createdAt: '2022-01-25T10:38:12+05:30',
              updatedAt: '2022-05-14T17:45:43+05:30',
              userHandler: 'rohan',
              pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423482/mypic-removebg-removebg-preview_1_y2dfmv.jpg',
              link: 'https://rohanspage.netlify.app',
              bio: 'Aspiring Software Developer',
              followers: [],
              following: [
                {
                  _id: 'asassddsd243434',
                  firstName: 'Rajani',
                  lastName: 'Ghosh',
                  username: 'rajanighosh@gmail.com',
                  password: '1234abcd',
                  createdAt: '2022-03-21T10:12:12+05:30',
                  updatedAt: '2022-05-14T17:44:37+05:30',
                  userHandler: 'rajani',
                  pic: 'https://res.cloudinary.com/donqbxlnc/image/upload/v1652423672/images_oxp7vm.jpg',
                  link: 'https://rajani.netlify.app',
                  bio: 'Social Media Influencer',
                  followers: [],
                  following: [],
                  bookmarks: [],
                  id: '2',
                },
              ],
              bookmarks: [],
              id: '1',
            },
          ],
          following: [],
          bookmarks: [],
          id: '4',
        },
        replies: [],
        votes: {
          upvotedBy: [],
        },
        createdAt: '2022-05-14T18:01:24+05:30',
        updatedAt: '2022-05-14T18:01:24+05:30',
      },
    ],
    username: 'devikagill@gmail.com',
    createdAt: '2022-05-14T18:00:11+05:30',
    updatedAt: '2022-05-14T18:01:02+05:30',
    id: '9',
  },
  {
    _id: '4abf2075-d0d6-4a7b-9e9a-23ecd3cdcc29',
    content:
      'Got rejected from google Today. Not able to solve leetcode medium questions🙃',
    pic: '',
    userId: 'asassddfd232fgfg323',
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    comments: [],
    username: 'suhashdugar@gmail.com',
    createdAt: '2022-05-14T18:00:57+05:30',
    updatedAt: '2022-05-14T18:00:57+05:30',
    id: '10',
  },
  {
    _id: 'a5648446-4a9e-433c-9db5-7f09f96d8da0',
    content: 'Today I heard about Neog.camp seems interesting to me🤩',
    pic: '',
    userId: 'asassddfd232fgfg323',
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    comments: [],
    username: 'suhashdugar@gmail.com',
    createdAt: '2022-05-14T18:04:24+05:30',
    updatedAt: '2022-05-14T18:04:24+05:30',
    id: '11',
  },
  {
    _id: '35c8a9c6-ad31-47f3-97ec-1fe94ac82791',
    content:
      'Learned about segmentation Tree today, and able to solve 3 questions by myself😎',
    pic: '',
    userId: 'asassddsd243434',
    likes: {
      likeCount: 0,
      likedBy: [],
      dislikedBy: [],
    },
    comments: [],
    username: 'rajanighosh@gmail.com',
    createdAt: '2022-05-14T18:06:06+05:30',
    updatedAt: '2022-05-14T18:06:06+05:30',
    id: '12',
  },
];
